name: Deploy to server using SSH - Plugin project

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: "The environment to deploy to."
        options:
          - production
          - staging
        required: true
        default: "staging"
  push:
    branches:
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Token used for storing AWS session
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build WordPress and deploy to server
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT != '' && inputs.ENVIRONMENT || 'staging' }}
    strategy:
      fail-fast: false

    steps:
      - name: Setup WordPress
        uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/wordpress@main
        with:
          PHP_VERSION: "8.3"
          WORDPRESS_GH_ACTIONS: ${{ secrets.WORDPRESS_GH_ACTIONS }}

      - name: Setup custom secrets as environment variables
        shell: bash
        run: |
          wp config set AUTH_KEY '${{ secrets.AUTH_KEY }}'
          wp config set SECURE_AUTH_KEY '${{ secrets.SECURE_AUTH_KEY }}'
          wp config set LOGGED_IN_KEY '${{ secrets.LOGGED_IN_KEY }}'
          wp config set NONCE_KEY '${{ secrets.NONCE_KEY }}'
          wp config set AUTH_SALT '${{ secrets.AUTH_SALT }}'
          wp config set SECURE_AUTH_SALT '${{ secrets.SECURE_AUTH_SALT }}'
          wp config set LOGGED_IN_SALT '${{ secrets.LOGGED_IN_SALT }}'
          wp config set NONCE_SALT '${{ secrets.NONCE_SALT }}'
          wp config set WP_CACHE_KEY_SALT '${{ secrets.WP_CACHE_KEY_SALT }}'
          wp config set WP_ENVIRONMENT_TYPE '${{ inputs.ENVIRONMENT != '' && inputs.ENVIRONMENT || 'staging' }}'

      - name: Set special constants
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/special-constants@main

      - name: Install all plugins
        uses: infinum/eightshift-deploy-actions-public/.github/actions/plugins/install@main
        with:
          WORDPRESS_GH_ACTIONS: ${{ secrets.WORDPRESS_GH_ACTIONS }}

      - name: Install plugin
        uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/theme-or-plugin@main
        with:
          PROJECT_PATH: wp-content/plugins/<plugin_name>
          USE_BUN: true

      - name: Set cache
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/cache@main
        with:
          PROJECT_PATH: wp-content/plugins/<plugin_name>

      - name: Update version number
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/version-plugin@main
        with:
          PROJECT_PATH: wp-content/plugins/<plugin_name>

      - name: Setup real database constants
        shell: bash
        run: |
          wp config set DB_NAME '${{ secrets.DB_NAME }}'
          wp config set DB_USER '${{ secrets.DB_USER }}'
          wp config set DB_PASSWORD '${{ secrets.DB_PASSWORD }}'
          wp config set DB_HOST '${{ secrets.DB_HOST }}'

      - name: Post install cleanup - root
        uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup/root@main

      - name: Post install cleanup - project
        uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup/project@main
        with:
          PROJECT_PATH: wp-content/plugins/<plugin_name>

      - name: Setup correct folder/file permissions
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/permissions@main

      - name: Deploy to server
        uses: infinum/eightshift-deploy-actions-public/.github/actions/ssh/server-deploy@main
        with:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_ROOT: ${{ secrets.SERVER_ROOT }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SSM_DEPLOY: true
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ROLE: ${{ secrets.AWS_ROLE }}

      - name: Notify
        uses: infinum/eightshift-deploy-actions-public/.github/actions/slack-notification@main
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
